### ISSUE TITLE
Slack invite link is expired

### ISSUE THREAD

**Issue by sethbattin** [siddharthkp/bundlesize#175] opened 2017-10-26 03:09 UTC
**Do you want to request a *feature* or report a *bug*?**
### What is the current behavior?
The slack invitation link in [Contributing](https://github.com/siddharthkp/bundlesize/blob/master/CONTRIBUTING.md#click-here-to-join-the-slack-channel) is expired.
![image](https://user-images.githubusercontent.com/1627760/32033177-aafa0e6a-b9d0-11e7-96a4-b3fb831fe94a.png)

### If the current behavior is a bug, please provide the steps to reproduce.

click: https://join.slack.com/t/bundlesize/shared_invite/MjMyNTA0NjUwNzg5LTE1MDM4NjAxNjEtMjFjZThlZmIxMw

### What is the expected behavior?
:slack:

**Comment by sreetamdas** [comment] 2017-10-26 10:29
seems to working just fine

**Comment by palashmon** [comment] 2018-06-10 15:54
Duplicate of #177

**Closed by palashmon** 2018-06-10 15:54 UTC
