### ISSUE TITLE
Update slack links 

### ISSUE THREAD

**Issue by jakebolam** [siddharthkp/bundlesize#216] opened 2018-04-15 18:17 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Slack links are broken

**If the current behavior is a bug, please provide the steps to reproduce.**
Slack links from the README.md and CONTRIBUTING.d are currently broken.
- README links to https://bundlesize.now.sh/ which redirects to a 404
- CONTRIBUTING links to https://join.slack.com/t/bundlesize/shared_invite/MjMyNTA0NjUwNzg5LTE1MDM4NjAxNjEtMjFjZThlZmIxMw which errors with _Invite link no longer active_

**What is the expected behavior?**
Slack links work

**If this is a feature request, what is motivation or use case for changing the behavior?**
Slack is important for contributors. Using slack ensures developers have an easy way to connect. This will help promote active contributions to bundlesize.

** I'm happy to create and start promoting a new slack workspace. Even better if someone has access to the previous one reinvigorate it

**Comment by palashmon** [comment] 2018-06-10 15:54
Duplicate of #177

**Closed by palashmon** 2018-06-10 15:54 UTC
